cuda_compiler_version:                          # [linux64]
  - None                                        # [linux64]
docker_image:                                   # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux64]
cudnn:                                          # [linux64]
  - undefined                                   # [linux64]
cdt_name:                                       # [linux64]
  - cos7                                        # [linux64]

c_stdlib_version:         # [osx and x86_64]
  - "10.15"               # [osx and x86_64]
MACOSX_SDK_VERSION:       # [osx and x86_64]
  - "10.15"               # [osx and x86_64]

# see https://github.com/conda-forge/ray-packages-feedstock/pull/152#issuecomment-2015479106
libgrpc:
- '1.59'

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
