cuda_compiler_version:                          # [linux64]
- None                                          # [linux64]
docker_image:                                   # [linux64]
- quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
cudnn:                                          # [linux64]
- undefined                                     # [linux64]
cdt_name:                                       # [linux64]
- cos7                                          # [linux64]
c_compiler_version:                             # [linux64]
- 13                                            # [linux64]
cxx_compiler_version:                           # [linux64]
- 13                                            # [linux64]
c_stdlib_version:         # [osx and x86_64]
- '10.15'                 # [osx and x86_64]
MACOSX_SDK_VERSION:       # [osx and x86_64]
- '10.15'                 # [osx and x86_64]
github_actions_labels:
- cirun-openstack-cpu-4xlarge
